# Generated by Django 4.0.4 on 2022-04-22 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_event_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='meeting_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='meetingminutes',
            old_name='meeting_id',
            new_name='meeting',
        ),
    ]
